### ISSUE TITLE
Any Plan to Merge with Speckle Sharp

### ISSUE THREAD

**Issue by chuongmep** [urbansurgery/rimshot#42]
**Is your feature request related to a problem? Please describe.**
Hi @jsdbroughton , do you have any plan to merge with speckle-sharp github to develop support for navisworks ? 

**Describe the solution you'd like**
Add connector support Navisworks to https://github.com/specklesystems/speckle-sharp

**Describe alternatives you've considered**

**Additional context**

**Comment by jsdbroughton** [comment]
That's quite an idea!

**Comment by chuongmep** [comment]
@jsdbroughton Thanks you, I will follow this repo , nice idea.
